### ISSUE TITLE
Segfault and xrootd server reboot every few minutes

### ISSUE THREAD

**Issue by cabrillo** [xrootd/xrootd#1335]
Dear,
   Trying to  deploy xrootd server for cms VO uncer CentOS7, read and writes works fine, but server crash/restart every few minutes. The lcmaps use an Argus endpoint   (this Argus endpoint is working for production deployment under sl6 with 8 xrootd servers ).

   these are the xrootd installed packages:
   xrootd-libs-4.12.4-1.el7.x86_64
   xrootd-cmstfc-1.5.2-6.osg35.el7.x86_64
   xrootd-voms-4.12.4-1.el7.x86_64
   xrootd-server-4.12.4-1.el7.x86_64
   xrootd-client-4.12.4-1.el7.x86_64
   xrootd-selinux-4.12.4-1.el7.noarch
   xrootd-4.12.4-1.el7.x86_64
   xrootd-lcmaps-1.7.8-2.osg35.el7.x86_64
   xrootd-server-libs-4.12.4-1.el7.x86_64
   xrootd-client-libs-4.12.4-1.el7.x86_64
   lcmaps-plugins-c-pep-1.3.1-1.el7.x86_64
   argus-pep-api-c-2.3.0-2.el7.centos.x86_64

  The error I can see is this:
.................................
lcmaps[11929]     LOG_ERR: 2020-11-20.10:16:07Z: pepapi_log: pep_authorize: NULL mandatory option PEP_OPTION_ENDPOINT_URL
lcmaps[11929]     LOG_ERR: 2020-11-20.10:16:07Z: pepc_engage: pep_authorize() failed for endpoint https://XXXXXXXXXXXX:8154/authz: "NULL pointer error"
lcmaps[11929]     LOG_ERR: 2020-11-20.10:16:07Z: pepapi_log: pep_llist_delete_elements: NULL pointer list.
lcmaps[11929]     LOG_ERR: 2020-11-20.10:16:07Z: pepapi_log: pep_llist_delete: NULL pointer list.
*** Error in `/usr/bin/xrootd': free(): invalid pointer: 0x00007fb52c115090 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7fb54870d299]
/usr/lib64/lcmaps/lcmaps_c_pep.mod(pepc_cleanup+0x2f)[0x7fb541e46a6f]
/usr/lib64/lcmaps/lcmaps_c_pep.mod(+0x890e)[0x7fb541e4790e]
/lib64/liblcmaps.so.0(lcmaps_runEvaluationManager+0xc1)[0x7fb543dd1631]
/lib64/liblcmaps.so.0(lcmaps_runPluginManager+0x2d3)[0x7fb543dcc573]
/lib64/liblcmaps.so.0(lcmaps_run_with_pem_and_return_account+0x363)[0x7fb543dc4b23]
/lib64/libXrdLcmaps-4.so(XrdSecgsiAuthzFun+0x45a)[0x7fb543fe1bfa]
/usr/lib64/libXrdSecgsi-4.so(_ZN17XrdSecProtocolgsi12AuthenticateEP12XrdSecBufferPS1_P13XrdOucErrInfo+0x12ef)[0x7fb545aa3e1f]
/lib64/libXrdServer.so.2(_ZN17XrdXrootdProtocol7do_AuthEv+0x195)[0x7fb549b92875]
/lib64/libXrdUtils.so.2(_ZN7XrdLink4DoItEv+0x19)[0x7fb54990be49]
/lib64/libXrdUtils.so.2(_ZN12XrdScheduler3RunEv+0x17f)[0x7fb54990f1df]
/lib64/libXrdUtils.so.2(_Z15XrdStartWorkingPv+0x9)[0x7fb54990f329]
/lib64/libXrdUtils.so.2(XrdSysThread_Xeq+0x37)[0x7fb5498d4be7]
/lib64/libpthread.so.0(+0x7ea5)[0x7fb549488ea5]
/lib64/libc.so.6(clone+0x6d)[0x7fb54878a96d]
.................................
There is no error at argus server side.
Any advise is welcomed.
Regards, I

**Comment by abh3** [comment]
Yes, I see that but oit would appear that the expectations of the 
combined package are in conflict. I think this is one that OSG needs to 
address. My take is that there is an incompatible mix of plugins.

**Comment by cabrillo** [comment]
Hi,
   The dmesg show always segfault at the same lib:
   173250.829590] traps: xrootd[13854] general protection ip:7f8d7ae977e5 sp:7f8d741f99b8 error:0 in libargus-pep.so.2.1.0[7f8d7ae91000+22000]
[173279.577867] xrootd[16735]: segfault at 0 ip 00007fc33d012af6 sp 00007fc3418379c0 error 6 in libargus-pep.so.2.1.0[7fc33d00c000+22000]

from package argus-pep-api-c

**Comment by abh3** [comment]
I think tha shows that a plugin in the path is causing the problem. If 
you can provide a stack trace that would help identifying the plugin at 
fault.

**Comment by xrootd-dev** [comment]
OK, I see that you did proide a stack trace but, unfortunately, it does 
have statement numbers (not that it was something you can control). Is 
there a core file? If there is, perahps you can get a backtrace from that.

Andy

**Comment by cabrillo** [comment]
Hi Guys,
   I attach the strace from start to crash. I hope this help[
[xrootd.v4.12.crash.log](https://github.com/xrootd/xrootd/files/5573745/xrootd.v4.12.crash.log)
](url)

**Comment by bbockelm** [comment]
Hi @cabrillo -

Who is upstream for `lcmaps_c_pep.mod`?  Judging from the function names, it looks like there's an issue in tear-down.  The OSG-supported LCMAPS modules required a few bugfixes to ensure they could be invoked over-and-over without leaks or segfaults.  Since `lcmaps_c_pep.mod` isn't part of the OSG stack, we certainly haven't tested it with the xrootd setup so I'm afraid I don't have much solid advice to offer.

Brian

**Comment by cabrillo** [comment]
Hi Brian,
   This package seems to be part of Argus deployment from nikhef.
   I just find an older version of￼ lcmaps-plugins-c-pep at nikhef repo, and seems that server is stable at least since a couple of hours, the version at nikhef repo is lcmaps-plugins-c-pep-1.2.6-1.el7.x86_64.rpm instead of latest available at UMD repo lcmaps-plugins-c-pep-1.3.1-1.el7.x86_64. 
Regards, I

**Comment by abh3** [comment]
Has this been resolved?

**Comment by abh3** [comment]
Given no response as to the resolution I can only assume this has been resolved.

**Comment by pavel-demin** [comment]
Unfortunately, this issue is still not resolved. I have just created a [GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=151824) to bring this issue to the attention of ARGUS developers.

**Comment by msalle** [comment]
Hi, we'll need to have a look, but from https://github.com/xrootd/xrootd/issues/1335#issuecomment-731113297 it's not really clear where the cause is. The LCMAPS plugin seems to be passing a NULL value as endpoint to the libargus-pep library, which then fails and ultimately causes a invalid cleanup in the latter (libargus-pep) which causes the SEGV. The question is how libargus-pep has a NULL value for the endpoint URL in https://github.com/argus-authz/argus-pep-api-c/blob/EMI-3/src/argus/pep.c#L492
while the LCMAPS plugin prints out a valid endpoint in https://ndpfsvn.nikhef.nl/viewvc/mwsec/tags/lcmaps-plugins-c-pep/1_3_1/src/c-pep/pep-c-interact.c?revision=18508&view=markup#l561?
Is it possible that there is something odd in the config? It seems that somehow the pep_handle looses its endpoint, but it's not clear to me where that would happen.
Is xrootd trying to call LCMAPS in a multi-threaded environment? That could be the issue (LCMAPS is not threadsafe).
We would definitely need more logging to be able to say what's happening. Enabling LCMAPS debug logging (by setting `export LCMAPS_DEBUG_LEVEL=5`) would definitely help a lot. Also, we'd need the `lcmaps.db` file. Perhaps best to attach those to the GGUS ticket.

**Comment by abh3** [comment]
Well, I think you have found the problem. Indeed, all plugins are are called in a multi-threaded way and unless the plugin has some thread protection (I have no idea if the LCMAPS plugin does) then you will undoubtedly see aberrant behavior, including SEGV's.

**Comment by msalle** [comment]
Hmm, no, neither LCMAPS nor any of the plugins was ever made thread safe and that's not really possible now. 
Is there an easy way to protect it from xrootd side, forcing it to run single-threaded?
It is still a bit surprising that we wouldn't have seen this before in xrootd though. I'm wondering if we're missing something else.

**Comment by xrootd-dev** [comment]
There is no way to make xrootd run single-threaded. SOmeone will simply 
need to put a mutex in the plugin (or wrap the plugin with such a mutex 
gaurd) to keep it from blowing up. The wrapping part would likely be the 
easier approach.

Andy

**Comment by msalle** [comment]
Indeed, I was thinking it could perhaps be done in xrootd-lcmaps which I think is doing the actual calling of LCMAPS and hence the obvious place. I think it's written by @bbockelm ?

**Comment by abh3** [comment]
Yes, I think @bbockelm wrote that and I would be suprised if he didn't 
make the wrapper single thread the calls to that library. So, perhaps 
there is lock call missing for some call.

On Mon, 3 May 2021, msalle wrote:

> Indeed, I was thinking it could perhaps be done in xrootd-lcmaps which 
I think is doing the actual calling of LCMAPS and hence the obvious 
place. I think it's written by @bbockelm ?

**Comment by pavel-demin** [comment]
> We would definitely need more logging to be able to say what's happening. Enabling LCMAPS debug logging (by setting export LCMAPS_DEBUG_LEVEL=5) would definitely help a lot. Also, we'd need the lcmaps.db file. Perhaps best to attach those to the GGUS ticket.

I have attached to the GGUS ticket lcmaps.db and a log file with LCMAPS_DEBUG_LEVEL set to 5.

The XRootD server crashes when a request using XRootD protocol is followed by a request using HTTP:
```
xrd ... (works)
davix-get ... (server crashes)
```

**Comment by msalle** [comment]
I might have found an issue. I think the bug is probably in xrootd-lcmaps, where it fails to reinitialize LCMAPS, but runs the plugin twice. I need to investigate a bit further but seem to have reproduced the issue.

**Comment by msalle** [comment]
No, I actually found an issue with the cleanup code in the lcmaps_c_pep plugin and probably can fix this quite easily.
I managed to reproduce the SEGV and after fixing could run the plugin twice without problems.
The point is that the plugin runs twice in the same process and doesn't properly reset all its static variables.
I'll try to make a release in the next few days.

**Comment by msalle** [comment]
Hi @pavel-demin could you try the new plugin:

- RHEL7: http://software.nikhef.nl/dist/mwsec/rpm/testing/epel7/x86_64/lcmaps-plugins-c-pep-1.3.2-1.el7.x86_64.rpm
- RHEL8: http://software.nikhef.nl/dist/mwsec/rpm/testing/epel8/x86_64/lcmaps-plugins-c-pep-1.3.2-1.el8.x86_64.rpm

They are signed with Nikhef key. If this fixes indeed the issue, I will push it to the UMD.

**Comment by pavel-demin** [comment]
I have tried the RPM package for RHEL7 and it works without crashing XRootD. Thank you for solving this problem.

**Comment by cabrillo** [comment]
Thanks a lot guys. I will try this new plugging asap.Regards, ISent from Android deviceEl 5 may. 2021 22:37, Pavel Demin ***@***.***> escribió:
I have tried the RPM package for RHEL7 and it works without crashing XRootD. Thank you for solving this problem.

**Comment by msalle** [comment]
Hi @cabrillo 
note that I have just move the packages to our release repo:

- RHEL7: https://software.nikhef.nl/dist/mwsec/rpm/epel7/x86_64/lcmaps-plugins-c-pep-1.3.2-1.el7.x86_64.rpm
- RHEL8: https://software.nikhef.nl/dist/mwsec/rpm/epel8/x86_64/lcmaps-plugins-c-pep-1.3.2-1.el8.x86_64.rpm

I will also ask the UMD to update.

**Comment by cabrillo** [comment]
HI Guys,
   Adter lcmaps-plugins-c-pep update and restart the service I still see the same behaviour:

ay  6 09:15:44 pool01 systemd: xrootd@clustered.service failed.
May  6 09:15:44 pool01 systemd: xrootd@clustered.service has no holdoff time, scheduling restart.
May  6 09:15:44 pool01 systemd: Stopped XRootD xrootd daemon instance clustered.
May  6 09:15:44 pool01 systemd: Started XRootD xrootd daemon instance clustered.
May  6 09:16:56 pool01 systemd: xrootd@clustered.service: main process exited, code=killed, status=64/RTMIN+30
May  6 09:16:56 pool01 systemd: Unit xrootd@clustered.service entered failed state.
May  6 09:16:56 pool01 systemd: xrootd@clustered.service failed.
May  6 09:16:56 pool01 systemd: xrootd@clustered.service has no holdoff time, scheduling restart.
May  6 09:16:56 pool01 systemd: Stopped XRootD xrootd daemon instance clustered.
May  6 09:16:56 pool01 systemd: Started XRootD xrootd daemon instance clustered.
May  6 09:17:33 pool01 systemd: xrootd@clustered.service: main process exited, code=killed, status=64/RTMIN+30
May  6 09:17:33 pool01 systemd: Unit xrootd@clustered.service entered failed state.
May  6 09:17:33 pool01 systemd: xrootd@clustered.service failed.
May  6 09:17:33 pool01 systemd: xrootd@clustered.service has no holdoff time, scheduling restart.
May  6 09:17:33 pool01 systemd: Stopped XRootD xrootd daemon instance clustered.

using CentOS7 and these packages:

xrootd-lcmaps-1.7.8-2.osg35.el7.x86_64
lcas-lcmaps-gt4-interface-0.3.1-1.el7.x86_64
lcmaps-without-gsi-1.6.6-1.el7.x86_64
lcmaps-plugins-verify-proxy-1.5.9-1.el7.x86_64
lcmaps-plugins-basic-1.7.1-1.el7.x86_64
lcmaps-plugins-c-pep-1.3.2-1.el7.x86_64
lcmaps-plugins-tracking-groupid-0.1.3-1.el7.x86_64
lcmaps-1.6.6-1.el7.x86_64
lcmaps-plugins-voms-1.7.1-1.el7.x86_64
xrootd-client-libs-4.12.4-1.el7.x86_64
xrootd-4.12.4-1.el7.x86_64
xrootd-server-4.12.4-1.el7.x86_64
xrootd-client-4.12.4-1.el7.x86_64
xrootd-server-libs-4.12.4-1.el7.x86_64
xrootd-cmstfc-1.5.2-6.osg35.el7.x86_64
xrootd-voms-4.12.4-1.el7.x86_64
xrootd-libs-4.12.4-1.el7.x86_64
xrootd-selinux-4.12.4-1.el7.noarch
Regards, I

**Comment by msalle** [comment]
Hi @cabrillo 
I'm afraid I don't know much about xrootd, but are you sure this is still the same issue?
Would you be able to provide:
- logs containing LCMAPS's and the argus-pep debug logs:
  - make sure you have an `export LCMAPS_DEBUG_LEVEL=5`
  - if you don't have it, add to the module definition of the pep_c plugin a line containing `--pep-c-loglevel debug`
- your `lcmaps.db` file

Also, make sure you've restarted the service, since the plugin otherwise probably has not been reloaded.
