### ISSUE TITLE
Wrong posix permissions with third party copy

### ISSUE THREAD

**Issue by testrg** [xrootd/xrootd#1642]
Hi,
At our site we got transferred at times a lot of files with wrong POSIX permissions (0600) instead of the usual ones (0644). I think to have reproduced the issue, since by doing xrdcp with '--tpc only' the copied files indeed get 0600 , while transferring the same files with classical xrdcp they get the right permission mask. It looks like a bug if it is not something missing or wrong in the config or some other point I might be overlooking.
The destination data servers have XRootD v5.3.1.
As far as I can see in the logs on the data server the different permissions' masks between the two cases (with/without tpc) appear in these lines:
tpc only --> ofs_open: 200-40600 fn=/15/24913/07b16210-d6aa-11e8-93cf-dc4a3e8bf04f
classic   --> ofs_open: 100200-40644 fn=/15/24913/07b16210-d6aa-11e8-93cf-dc4a3e8bf04f
tpc only --> oss_Open_ufs: fd=32781 flags=202 mode=40600 path=/lustre/a/d/15/24913/07b16210-d6aa-11e8-93cf-dc4a3e8bf04f
classic   --> oss_Open_ufs: fd=32802 flags=202 mode=40644 path=/lustre/a/d/15/24913/07b16210-d6aa-11e8-93cf-dc4a3e8bf04f

Thanks in advance for your comments, cheers,
   Raffaele

**Comment by simonmichal** [comment]
@testrg : thanks for reporting this and sorry for the late replay, it should be fixed now by:
https://github.com/xrootd/xrootd/commit/21947f4d51805b8bd8cb257cd13093d8fb9d26ff

Could you give it a try?

**Comment by testrg** [comment]
One more point: wouldn't it be even better to have the file opened with the permissions decided by the local file system, in general by umask, as it happens when touching a new file? I mean instead of hard coding 644, although in the vast majority of cases 0644 is indeed what we want (and the default umask is 022).

**Comment by abh3** [comment]
Actually, we purposefully do not use the umask as it's very deceiving 
since it's associated with a user and a) the file creator is actually the 
daemon noot the user, and b) Certain plugins change the daemon's userid 
when creating a file. For simplicity and consistency we do not use the 
umask. However, we are considering allowing you to specify the mode on 
the xrdcp command line to provide more flexibility. The other possibility 
is to modify the client-side default or 0644 using the client-side umask. 
But even then, I think that would be somewhat confusing and may change 
past behaviour which we try to avoid.

Andy

**Comment by testrg** [comment]
OK.
Concerning the testing of this commit, I hope we find the time to try the master before the end of the week. I'll be in touch.

**Comment by abh3** [comment]
I surmize that this has been fixed. If not, please reopen.

**Comment by testrg** [comment]
Hi Andy,
sorry for the late testing. We installed v5.5.0, which contains the commit as far as I can see, but that didn't solve the issue. I can provide logs if that helps. I can't reopen the issue because I didn't close it (so works Github, as far as I understand).
Raffaele

**Comment by abh3** [comment]
All I really need is what you expected the permissions to be and what they actually wind up being. Is it consistently so?

**Comment by testrg** [comment]
I expect the permission to be '0644'. This is what we get with plain xrdcp, while we get '0600' with '--tpc only'. We get '0644' also e.g. with 'touch' directly on the file system. It is consistently so, it did not change with upgrading the data servers (and the redirectors) from v5.3.1 to v5.5.0.

**Comment by testrg** [comment]
Are there news on this, possibly changes in v5.5.1 to be tested?
We will probably soon move the data servers to Rocky 8, there are however no particular reason to expect that this move will have any impact on this issue, right?
BTW, I think I forgot to say that the files are written to our Lustre instance, in case that can matter.

**Comment by testrg** [comment]
For completeness I am adding here too the observation that the issue appears to be solved when the client XRootD version is >= 5.5.0.
