### ISSUE TITLE
Client documentation on XRootD website is outdated

### ISSUE THREAD

**Issue by amadio** [xrootd/xrootd#2209]
The documentation at https://xrootd.slac.stanford.edu/doc/xrdcl-docs/www/xrdcldocs.html is from 2019, it should be updated and re-uploaded.

**Comment by abh3** [comment]
Sure, but can you point me to the pdf version as well? The webpage has both, so I know both should exist. Likely it was generated from an MS Word document.
________________________________
From: Guilherme Amadio ***@***.***>
Sent: Monday, March 4, 2024 6:06 AM
To: xrootd/xrootd ***@***.***>
Cc: Andrew Hanushevsky ***@***.***>; Assign ***@***.***>
Subject: [xrootd/xrootd] Client documentation on XRootD website is outdated (Issue #2209)


The documentation at https://xrootd.slac.stanford.edu/doc/xrdcl-docs/www/xrdcldocs.html is from 2019, it should be updated and re-uploaded.

**Comment by amadio** [comment]
Hi Andy, the docs I mentioned above are the `XRootD Client Configuration & API Reference` which can be found at https://xrootd.slac.stanford.edu/docs.html. The html and pdf pages are both linked there and from 2019.

**Comment by abh3** [comment]
The problem has been corrected.

**Comment by amadio** [comment]
Thank you Andy! Unfortunately, I think we still will need a further update, as I still see
```
-X | --xrate rate [NOT YET IMPLEMENTED]
```
in the current documentation. It's from 2022.

**Comment by abh3** [comment]
The problem is that is all I have. Michal updated the document products but did not change the date on the web page. So, that's what I corrected. Unless you can find the original doc (MS word or Google doc - I don't know which he used) this is going to be a big problem.
________________________________

**Comment by amadio** [comment]
Ok, let me reopen this and take the ticket, since this is about the client documentation. I will figure out how to build an updated version of the docs and push to the website when I release 5.7.

**Comment by amadio** [comment]
It seems the docs on the website are based on https://github.com/simonmichal/xrdcl-docs so we will need to manually update it to sync with the current man pages or migrate everything to a new system, to be defined.

**Comment by abh3** [comment]
Well, that was a surprise! At the very least we should copy it into out repo as we have control over the lifetime. You would think those files were actually created by some html editing tool. Maybe we should ask him what he used?
________________________________

**Comment by amadio** [comment]
It's just a latex document, likely based on the manual page for xrdcp.

**Comment by abh3** [comment]
Figures that Latex was used here. I'd rather not go further down that rat hole. Let's figure out what else can be done here. However, I do know the options are quite limited.
________________________________

**Comment by amadio** [comment]
This is a good topic to discuss at the workshop. I think we can copy what some established project does, like the [kernel](https://docs.kernel.org/doc-guide/sphinx.html) or [git](https://github.com/git/git/tree/master/Documentation).
