### ISSUE TITLE
XrdOucString::endswith is buggy

### ISSUE THREAD

**Issue by apeters1971** [xrootd/xrootd#260]
If the the suffix string to test has one character more then the string to check, the function claims that XrdOucString ensdwith (s), e.g.

XrdOucString ew = "abcd";

ew.endswith("abcde") => true

because STR_NPOS=-1
 
```
//______________________________________________________________________________
bool XrdOucString::endswith(const char *s)
{
// returns 1 if the stored string ends with string s
return (s ? (rfind(s) == (int)(len-strlen(s))) : 0);
}
```

The character function has probably the same issue when the XrdOucString is empty:

```
//______________________________________________________________________________
bool XrdOucString::endswith(char c)
{
// returns 1 if the stored string ends with string s
return (rfind(c) == (int)(len-1));
}

**Comment by gganis** [comment]
Right. Should be fixed in the master.
Do you need to propagate it to other branches?

**Comment by apeters1971** [comment]
You didn't fix the equivalent function with a single character as input!

I have to grep my code how dangerous this bug is because I use XrdOucString
quite a lot!

Cheers Andreas.

**Comment by gganis** [comment]
Sorry. Done.

**Comment by abh3** [comment]
For some reason this was not closed with the commit message. So, I am doing it now. It was fixes with commits 6b4e3aec and 9c541c5d just hours ago.
