### ISSUE TITLE
"UNLIMITED" nproc limit is handled incorrectly

### ISSUE THREAD

**Issue by PerilousApricot** [xrootd/xrootd#288]
It appears that if the xrootd daemon is started with the nprocess limit set to UNLIMITED, it gets upside down:

```
Config maximum number of threads restricted to -1
<snip>
150916 13:04:40 12143 XrdScheduler: Thread limit has been reached!
```
(full log at bottom)
(shoutout to @bbockelm who noticed what I had just skimmed right past. :raising_hand:)

The behavior changed somehow between 3.x and 4.2.2 - the same box worked fine until xrootd was upgraded.

Copr.  2004-2012 Stanford University, xrd version v4.2.2
++++++ cmsd lfs@se8.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-lfs.cfg
=====> xrd.port 1094
=====> xrd.trace conn
=====> all.adminpath /var/run/xrootd
Config maximum number of connections restricted to 65536
Config maximum number of threads restricted to -1
150916 13:04:40 12143 XrdConfig: sendfile enabled.
150916 13:04:40 12145 XrdXeq: Buffer Manager reshaper thread started
150916 13:04:40 12143 XrdSched: scheduling underused thread monitor in 780 seconds
150916 13:04:40 12146 XrdXeq: Time scheduler thread started
150916 13:04:40 12143 XrdScheduler: Thread limit has been reached!
150916 13:04:40 12143 XrdSched: Starting with 0 workers
150916 13:04:40 12143 XrdLink: Allocating 8 link objects at a time
150916 13:04:40 12143 XrdPoll: Starting poller 0
150916 13:04:40 12147 XrdXeq: Poller thread started
150916 13:04:40 12143 XrdPoll: Starting poller 1
150916 13:04:40 12148 XrdXeq: Poller thread started
150916 13:04:40 12143 XrdPoll: Starting poller 2
150916 13:04:40 12149 XrdXeq: Poller thread started
150916 13:04:40 12143 XrdProtocol: getting port from protocol cmsd
Copr.  2007 Stanford University/SLAC cmsd.
++++++ lfs@se8.accre.vanderbilt.edu phase 1 initialization started.
=====> all.role server
=====> all.manager se1.accre.vanderbilt.edu:1214
Config cms-xrd-transit.cern.ch -> all.manager vocms027.cern.ch
=====> all.manager cms-xrd-transit.cern.ch+ 1213
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export / nostage
=====> cms.trace all debug
=====> all.adminpath /var/run/xrootd
=====> all.pidpath /var/run/xrootd
The following paths are available to the redirector:
w  /
 
```
------ lfs@se8.accre.vanderbilt.edu phase 1 server initialization completed.
150916 13:04:40 12143 XrdConfig: LCL port 55165 wsz=10000000 (10000000)
150916 13:04:40 12143 XrdProtocol: getting protocol object cmsd
++++++ lfs@se8.accre.vanderbilt.edu phase 2 server initialization started.
150916 13:04:40 12143 Configure2 Global System Identification: lfs-s 1214se1.accre.vanderbilt.edu1213vocms027.cern.ch
++++++ Storage system initialization started.
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export / nostage
Plugin No such file or directory loading namelib /usr/lib64/libXrdCmsTfc-4.so
Config Falling back to using /usr/lib64/libXrdCmsTfc.so
Plugin loaded unversioned XrdOucgetName2Name from namelib /usr/lib64/libXrdCmsTfc.so
Copr. 2009 University of Nebraska-Lincoln TFC plugin v 1.0
Params: file:/etc/xrootd/storage-lfs.xml?protocol=direct
Xerces-c has been initialized.
Connecting to the catalog file:/etc/xrootd/storage-lfs.xml?protocol=direct
Using catalog file /etc/xrootd/storage-lfs.xml
++++++ Configuring standalone mode . . .
150916 13:04:40 12143 oss_AioInit: started AIO read signal thread; tid=889157376
150916 13:04:40 12143 oss_AioInit: started AIO write signal thread; tid=888104704
No lfn2pfn mapping for /
No lfn2pfn mapping for /
No lfn2pfn mapping for /
Config effective /etc/xrootd/xrootd-lfs.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32768 65536
       oss.maxsize      0
       oss.namelib /usr/lib64/libXrdCmsTfc.so
       oss.trace        fff
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751543808
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path / r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
150916 13:04:40 12143 Start Srv=0 dfs=0 lcl=0 Pre=1 dmLife=0 0
150916 13:04:40 12143 Start Lim=0 0 fix=0 Qmax=1
150916 13:04:40 12143 calcSpace New fs info; maxfree=819722MB utilized=7%
150916 13:04:40 12143 Meter: Found 1 filesystem(s); 854GB total (7% util); 800GB free (800GB max)
150916 13:04:40 12220 XrdXeq: FS meter thread started
------ lfs@se8.accre.vanderbilt.edu phase 2 server initialization completed.
------ cmsd lfs@se8.accre.vanderbilt.edu:55165 initialization completed.
150916 13:24:40 12145 XrdBuffManager: Reshaper has 0K; target 6592098K
150916 13:44:40 12145 XrdBuffManager: Reshaper has 0K; target 6592098K
150916 14:04:40 12145 XrdBuffManager: Reshaper has 0K; target 6592098K
150916 14:24:40 12145 XrdBuffManager: Reshaper has 0K; target 6592098K
150916 14:44:40 12145 XrdBuffManager: Reshaper has 0K; target 6592098K
```

**Comment by abh3** [comment]
Hi Andrew,

That problem existed in the early 4.x releases. The reason is that 
unlimited set the nproc value to -1 and xrootd din't know how to handle 
it. It got fixed in 4.1.1 though I'd sugggest going to 4.2.3.

Andy

**Comment by PerilousApricot** [comment]
Hi Andy,

First off, you have a pretty swell name.

I don't know what to make of the bug being fixed in 4.1.1:
```
[root@se8 ~]# xrootd -v
v4.2.2
[root@se8 ~]# rpm -qa | grep xrootd
xrootd-libs-4.2.2-1.osg32.el6.x86_64
xrootd-selinux-4.2.2-1.osg32.el6.noarch
xrootd-server-4.2.2-1.osg32.el6.x86_64
xrootd-client-4.2.2-1.osg32.el6.x86_64
xrootd-lcmaps-0.0.7-11.osg32.el6.x86_64
xrootd-client-libs-4.2.2-1.osg32.el6.x86_64
xrootd-4.2.2-1.osg32.el6.x86_64
xrootd-server-libs-4.2.2-1.osg32.el6.x86_64
xrootd-cmstfc-1.5.1-10.osg32.el6.x86_64
cms-xrootd-1.2-9.osg32.el6.noarch
```

Are you and OSG somehow out of sync in the versioning? To hack things together and get something working, I started the services with ```(ulimit -u 1024 ; /etc/init.d/xrootd start ; /etc/init.d/cmsd start)```, and they worked fine. Dropping the ulimit and restarting again caused them to break. What do you think?

**Comment by xrootd-dev** [comment]
Might have regressed - as you can see in his log snippet, this was on 4.2.2.

Brian

**Comment by abh3** [comment]
Hi Brian,

The release numbers should sync between OSG and us. It definitely was 
fixed in 4.2.2. That said, I regressed as well. I misread nproc as the 
file descriptor limit. Please start xrootd (you can do this by hand on 
your own account as long maxproc is set to unlimited) with the -d option 
and send me the log file. Just do:

xrootd -d

no need for any config file to catch this problem. As for the nproc, 1024 
is way too small. It should usually be set to about 4K.

Andy

**Comment by PerilousApricot** [comment]
FWIW, as of the most current OSG(3.3) release, this bug still exists, but I missed the last of this thread asking for an update. Please find the following dump:

```
[root@se1 ~]# su - xroootd
su: user xroootd does not exist
[root@se1 ~]# su - xrootd
This account is currently not available.
[root@se1 ~]# su ^Cxrootd 
[root@se1 ~]# man su
[root@se1 ~]# su -s /bin/sh - xrootd
-sh-4.1$ ulimit -c
0
-sh-4.1$ xrootd -d
151105 16:46:22 38973 Starting on Linux 2.6.32-431.el6.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.2.3
++++++ xrootd anon@se1.accre.vanderbilt.edu initialization started.
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to -1
151105 16:46:22 38973 XrdConfig: sendfile enabled.
151105 16:46:22 38973 XrdSched: scheduling underused thread monitor in 780 seconds
151105 16:46:22 38973 XrdScheduler: Thread limit has been reached!
151105 16:46:22 38973 XrdSched: Starting with 0 workers
151105 16:46:22 38973 XrdLink: Allocating 8 link objects at a time
151105 16:46:22 38974 XrdXeq: Buffer Manager reshaper thread started
151105 16:46:22 38975 XrdXeq: Time scheduler thread started
151105 16:46:22 38973 XrdPoll: Starting poller 0
151105 16:46:22 38976 XrdXeq: Poller thread started
151105 16:46:22 38973 XrdPoll: Starting poller 1
151105 16:46:22 38977 XrdXeq: Poller thread started
151105 16:46:22 38973 XrdPoll: Starting poller 2
151105 16:46:22 38978 XrdXeq: Poller thread started
151105 16:46:22 38973 XrdProtocol: getting port from protocol xrootd
151105 16:46:22 38973 XrdConfig: LCL port 1094 wsz=87380 (87380)
151105 16:46:22 38973 XrdProtocol: getting protocol object xrootd
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.2.3
++++++ xrootd protocol initialization started.
Config warning: only '/tmp' will be exported.
Config warning: 'xrootd.seclib' not specified; strong authentication disabled!
Config Routing for se1.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se1.accre.vanderbilt.edu Dest=[::129.59.197.244]:1094
++++++ File system initialization started.
151105 16:46:22 38973 ofs_Config: Configuration file not specified.
++++++ Storage system initialization started.
Config warning: config file not specified; defaults assumed.
151105 16:46:22 38973 oss_AioInit: started AIO read signal thread; tid=4201457408
151105 16:46:22 38973 oss_AioInit: started AIO write signal thread; tid=4200404736
Config effective Default oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.trace        fff
       oss.xfr          1 deny 10800 keep 1200
151105 16:46:22 38981 XrdXeq: cache scan thread started
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
151105 16:46:22 38982 XrdXeq: Event receiver thread started
151105 16:46:22 38983 XrdXeq: Event flusher thread started
Config effective default ofs configuration:
       all.role server
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /tmp/.ofs/posc.log
       ofs.trace      bfcd
------ File system server initialization completed.
151105 16:46:22 38973 XrootdAioReq: Max aio/req=8; aio/srv=4096; Quantum=131072
151105 16:46:22 38973 XrootdAioReq: Adding 18 aioreq objects.
151105 16:46:22 38973 XrootdAio: Adding 18 aio objects; 4096 pending.
151105 16:46:22 38973 XrdSched: scheduling xrootd protocol anchor in 3600 seconds
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
151105 16:46:22 38984 XrdXeq: Admin traffic thread started
------ xrootd protocol initialization completed.
------ xrootd anon@se1.accre.vanderbilt.edu:1094 initialization completed.
[root@se1 ~]# xrootd -v
v4.2.3
[root@se1 ~]# yum info xrootd
Installed Packages
Name        : xrootd
Arch        : x86_64
Epoch       : 1
Version     : 4.2.3
Release     : 1.osg33.el6
```

**Comment by abh3** [comment]
Actually, it does work and when the limit is set to infinity, a limit of 127,000 is used. What the issue here is that the message was not removed in the fixed code (it only appears when debug is on). Yes, it is confusing but causes no harm and in some ways is correct as infinity is represented as -1 and the message simply says so.

**Comment by PerilousApricot** [comment]
Hi Andrew,
>
>
I don't know what's happening then.

I came back to this because I upgraded a second host from 3.x to the latest
package.

When I run the server without setting ulimit, it stops and doesn't serve
any requests. When I restart with a finite ulimit, it does. Can you help me
find what the difference is?

Thanks!
Andrew


-- 
It's dark in this basement.

**Comment by abh3** [comment]
Sure. So, the initialization complete message appears and the server does nothing afterwards right? So, just start the server with the '-d' option and send me the result. I'm not saying there still isn't a problem but the code looks OK.

**Comment by PerilousApricot** [comment]
That's what I see. Starting with the default ulimit goes through the
initializaton just stops and never appears to accept requests. After a bit,
if I stop the server and restart it with a new ulimit, requests immediately
flood in. The machine I upgraded is our site redirector, so it's constantly
being hammered.

I put a dump with "-d" in my previous message where it doesn't do anything.
Are there some other flags I could use to make it more verbose?

-- 
It's dark in this basement.

**Comment by PerilousApricot** [comment]
Here's a comparison. I start the server w/o a ulimit, tail the logs for 120 seconds, kill the server, start the server with a ulimit, and tail the logs for 120 seconds. Am I doing something wrong or just misinterpreting the server's behavior?

```
[root@se1 ~]# (ulimit -u ; rm -rf /var/log/xrootd/lfs/* ; /etc/init.d/cmsd stop ; /etc/init.d/xrootd stop ; sleep 10 ;  /etc/init.d/cmsd start ; /etc/init.d/xrootd start ; timeout 120 tail -n 100 -F /var/log/xrootd/lfs/*) ; echo "****** with ulimit" ; (ulimit -u 2048 ; ulimit -u ; rm -rf /var/log/xrootd/lfs/* ;  /etc/init.d/cmsd stop ; /etc/init.d/xrootd stop ; sleep 10 ;  /etc/init.d/cmsd start ; /etc/init.d/xrootd start ; timeout 120 tail -n 100 -F /var/log/xrootd/lfs/*)
unlimited
Shutting down xrootd (cmsd, lfs):                          [FAILED]
Shutting down xrootd (xrootd, lfs):                        [FAILED]
Starting xrootd (cmsd, lfs):                               [  OK  ]
Starting xrootd (xrootd, lfs):                             [  OK  ]
==> /var/log/xrootd/lfs/cmsd-lfs.log <==
151105 18:12:45 38262 Starting on Linux 2.6.32-431.el6.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.2.3
++++++ cmsd lfs@se1.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-lfs.cfg
=====> xrd.port 1094
=====> all.adminpath /var/run/xrootd
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to -1
151105 18:12:45 38262 XrdScheduler: Thread limit has been reached!
Copr.  2007 Stanford University/SLAC cmsd.
++++++ lfs@se1.accre.vanderbilt.edu phase 1 initialization started.
Config cmsxrootd.fnal.gov -> all.manager cmsxrootd1.fnal.gov
Config cmsxrootd.fnal.gov -> all.manager xrootd.unl.edu
=====> all.manager meta all cmsxrootd.fnal.gov+ 1213
=====> cms.delay servers 1 lookup 10
=====> all.role manager
=====> all.manager se1.accre.vanderbilt.edu:1214
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> cms.allow host *
=====> all.export /
=====> all.adminpath /var/run/xrootd
=====> all.pidpath /var/run/xrootd
=====> cms.delay startup 1
=====> cms.fxhold 10m
The following paths are available to the meta-manager:
w  /
 
------ lfs@se1.accre.vanderbilt.edu phase 1 manager initialization completed.
++++++ lfs@se1.accre.vanderbilt.edu phase 2 manager initialization started.
++++++ Storage system initialization started.
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export /
Plugin No such file or directory loading namelib /usr/lib64/libXrdCmsTfc-4.so
Config Falling back to using /usr/lib64/libXrdCmsTfc.so
Plugin loaded unversioned XrdOucgetName2Name from namelib /usr/lib64/libXrdCmsTfc.so
Copr. 2009 University of Nebraska-Lincoln TFC plugin v 1.0
Params: file:/etc/xrootd/storage-lfs.xml?protocol=direct
Xerces-c has been initialized.
Connecting to the catalog file:/etc/xrootd/storage-lfs.xml?protocol=direct
Using catalog file /etc/xrootd/storage-lfs.xml
++++++ Configuring standalone mode . . .
No lfn2pfn mapping for /
No lfn2pfn mapping for /
No lfn2pfn mapping for /
Config effective /etc/xrootd/xrootd-lfs.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.namelib /usr/lib64/libXrdCmsTfc.so
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path / r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
Config round robin scheduling in effect.
------ lfs@se1.accre.vanderbilt.edu phase 2 manager initialization completed.
------ cmsd lfs@se1.accre.vanderbilt.edu:1214 initialization completed.

==> /var/log/xrootd/lfs/xrootd-lfs.log <==
=====> all.adminpath /var/run/xrootd
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to -1
151105 18:12:45 38482 XrdScheduler: Thread limit has been reached!
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.2.3
++++++ xrootd protocol initialization started.
=====> xrootd.fslib throttle default
=====> all.export /
=====> xrootd.trace emsg login stall redirect
=====> xrootd.seclib /usr/lib64/libXrdSec.so
Config warning: ignoring fslib; libXrdOfs.so is built-in.
=====> xrootd.fslib /usr/lib64/libXrdOfs.so
=====> all.pidpath /var/run/xrootd
=====> xrootd.monitor all auth flush 30s mbuff 1472 window 5s dest files io info user xrootd.t2.ucsd.edu:9930
Config exporting /
Plugin loaded 
++++++ Authentication system initialization started.
Plugin loaded 
151105 18:12:45 38482 secgsi_InitOpts: *** ------------------------------------------------------------ ***
151105 18:12:45 38482 secgsi_InitOpts:  Mode: server
151105 18:12:45 38482 secgsi_InitOpts:  Debug: -1
151105 18:12:45 38482 secgsi_InitOpts:  CA dir: /etc/grid-security/certificates
151105 18:12:45 38482 secgsi_InitOpts:  CA verification level: 1
151105 18:12:45 38482 secgsi_InitOpts:  CRL dir: /etc/grid-security/certificates/
151105 18:12:45 38482 secgsi_InitOpts:  CRL extension: .r0
151105 18:12:45 38482 secgsi_InitOpts:  CRL check level: 1
151105 18:12:45 38482 secgsi_InitOpts:  CRL refresh time: 86400
151105 18:12:45 38482 secgsi_InitOpts:  Certificate: /etc/grid-security/xrd/xrdcert.pem
151105 18:12:45 38482 secgsi_InitOpts:  Key: /etc/grid-security/xrd/xrdkey.pem
151105 18:12:45 38482 secgsi_InitOpts:  Proxy delegation option: 0
151105 18:12:45 38482 secgsi_InitOpts:  GRIDmap file: /etc/grid-security/grid-mapfile
151105 18:12:45 38482 secgsi_InitOpts:  GRIDmap option: 1
151105 18:12:45 38482 secgsi_InitOpts:  GRIDmap cache entries expiration (secs): 600
151105 18:12:45 38482 secgsi_InitOpts:  Client proxy availability in XrdSecEntity.endorsement: 0
151105 18:12:45 38482 secgsi_InitOpts:  VOMS option: 1
151105 18:12:45 38482 secgsi_InitOpts:  MonInfo option: 1
151105 18:12:45 38482 secgsi_InitOpts:  Crypto modules: ssl
151105 18:12:45 38482 secgsi_InitOpts:  Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
151105 18:12:45 38482 secgsi_InitOpts:  MDigests: sha1:md5
151105 18:12:45 38482 secgsi_InitOpts: *** ------------------------------------------------------------ ***
151105 18:12:45 38482 secgsi_XrdOucGMap: cannot access grid map file '/etc/grid-security/grid-mapfile'in read mode; errno: 2 - aborting
=====> sec.protocol /usr/lib64 gsi -certdir:/etc/grid-security/certificates -cert:/etc/grid-security/xrd/xrdcert.pem -key:/etc/grid-security/xrd/xrdkey.pem -crl:1 -moninfo
Config 1 authentication directives processed in /etc/xrootd/xrootd-lfs.cfg
------ Authentication system initialization completed.
Config Routing for se1.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se1.accre.vanderbilt.edu Dest=[::129.59.197.244]:1094
++++++ File system initialization started.
=====> all.role manager
=====> ofs.authorize
++++++ Storage system initialization started.
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export /
Plugin No such file or directory loading namelib /usr/lib64/libXrdCmsTfc-4.so
Config Falling back to using /usr/lib64/libXrdCmsTfc.so
Plugin loaded unversioned XrdOucgetName2Name from namelib /usr/lib64/libXrdCmsTfc.so
Copr. 2009 University of Nebraska-Lincoln TFC plugin v 1.0
Params: file:/etc/xrootd/storage-lfs.xml?protocol=direct
Xerces-c has been initialized.
Connecting to the catalog file:/etc/xrootd/storage-lfs.xml?protocol=direct
Using catalog file /etc/xrootd/storage-lfs.xml
No lfn2pfn mapping for /
No lfn2pfn mapping for /
No lfn2pfn mapping for /
Config effective /etc/xrootd/xrootd-lfs.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.namelib /usr/lib64/libXrdCmsTfc.so
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path / r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
++++++ Authorization system initialization started.
151105 18:12:45 38482 acc_Config: Authorization system using configuration in /etc/xrootd/xrootd-lfs.cfg
=====> acc.authdb /etc/xrootd/Authfile
=====> acc.audit deny grant
Config 2 authorization directives processed in /etc/xrootd/xrootd-lfs.cfg
Config 1 auth entries processed in /etc/xrootd/Authfile
------ Authorization system initialization completed.
++++++ Configuring manager role. . .
=====> all.manager meta all cmsxrootd.fnal.gov+ 1213
=====> all.manager se1.accre.vanderbilt.edu:1214
=====> all.adminpath /var/run/xrootd
Config 1 manager(s) started.
Config effective /etc/xrootd/xrootd-lfs.cfg ofs configuration:
       all.role manager
       ofs.authorize
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /var/run/xrootd/lfs/.ofs/posc.log
       ofs.trace      0
------ File system manager initialization completed.
151105 18:12:45 38598 cms_Finder: Connected to cmsd via /var/run/xrootd/lfs/.olb/olbd.nimda
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
------ xrootd protocol initialization completed.
------ xrootd lfs@se1.accre.vanderbilt.edu:1094 initialization completed.
****** with ulimit
2048
Shutting down xrootd (cmsd, lfs):                          [  OK  ]
Shutting down xrootd (xrootd, lfs):                        [  OK  ]
Starting xrootd (cmsd, lfs):                               [  OK  ]
Starting xrootd (xrootd, lfs):                             [  OK  ]
==> /var/log/xrootd/lfs/cmsd-lfs.log <==
151105 18:14:56 6878 Starting on Linux 2.6.32-431.el6.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.2.3
++++++ cmsd lfs@se1.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-lfs.cfg
=====> xrd.port 1094
=====> all.adminpath /var/run/xrootd
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to 2048
Copr.  2007 Stanford University/SLAC cmsd.
++++++ lfs@se1.accre.vanderbilt.edu phase 1 initialization started.
Config cmsxrootd.fnal.gov -> all.manager xrootd.unl.edu
Config cmsxrootd.fnal.gov -> all.manager cmsxrootd1.fnal.gov
=====> all.manager meta all cmsxrootd.fnal.gov+ 1213
=====> cms.delay servers 1 lookup 10
=====> all.role manager
=====> all.manager se1.accre.vanderbilt.edu:1214
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> cms.allow host *
=====> all.export /
=====> all.adminpath /var/run/xrootd
=====> all.pidpath /var/run/xrootd
=====> cms.delay startup 1
=====> cms.fxhold 10m
The following paths are available to the meta-manager:
w  /
 
------ lfs@se1.accre.vanderbilt.edu phase 1 manager initialization completed.
++++++ lfs@se1.accre.vanderbilt.edu phase 2 manager initialization started.
++++++ Storage system initialization started.
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export /
Plugin No such file or directory loading namelib /usr/lib64/libXrdCmsTfc-4.so
Config Falling back to using /usr/lib64/libXrdCmsTfc.so
Plugin loaded unversioned XrdOucgetName2Name from namelib /usr/lib64/libXrdCmsTfc.so
Copr. 2009 University of Nebraska-Lincoln TFC plugin v 1.0
Params: file:/etc/xrootd/storage-lfs.xml?protocol=direct
Xerces-c has been initialized.
Connecting to the catalog file:/etc/xrootd/storage-lfs.xml?protocol=direct
Using catalog file /etc/xrootd/storage-lfs.xml
++++++ Configuring standalone mode . . .
No lfn2pfn mapping for /
No lfn2pfn mapping for /
No lfn2pfn mapping for /
Config effective /etc/xrootd/xrootd-lfs.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.namelib /usr/lib64/libXrdCmsTfc.so
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path / r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
Config round robin scheduling in effect.
------ lfs@se1.accre.vanderbilt.edu phase 2 manager initialization completed.
151105 18:14:56 6899 Start: Waiting for primary server to login.
------ cmsd lfs@se1.accre.vanderbilt.edu:1214 initialization completed.
151105 18:14:57 7009 do_Login:: Primary server 6988 logged in; data port is 1094
Config Connecting to 2 managers and 1 site.
151105 18:14:57 6883 Config: manager service enabled.
151105 18:14:57 7010 State: Status changed to suspended + nostaging
151105 18:14:57 6884 Protocol: redirector.6988:7@se1 logged in.

==> /var/log/xrootd/lfs/xrootd-lfs.log <==
=====> all.adminpath /var/run/xrootd
=====> all.sitename T2_US_Vanderbilt
=====> xrd.report xrootd.t2.ucsd.edu:9931 every 30s all sync
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to 2048
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.2.3
++++++ xrootd protocol initialization started.
=====> xrootd.fslib throttle default
=====> all.export /
=====> xrootd.trace emsg login stall redirect
=====> xrootd.seclib /usr/lib64/libXrdSec.so
Config warning: ignoring fslib; libXrdOfs.so is built-in.
=====> xrootd.fslib /usr/lib64/libXrdOfs.so
=====> all.pidpath /var/run/xrootd
=====> xrootd.monitor all auth flush 30s mbuff 1472 window 5s dest files io info user xrootd.t2.ucsd.edu:9930
Config exporting /
Plugin loaded 
++++++ Authentication system initialization started.
Plugin loaded 
151105 18:14:57 6988 secgsi_InitOpts: *** ------------------------------------------------------------ ***
151105 18:14:57 6988 secgsi_InitOpts:  Mode: server
151105 18:14:57 6988 secgsi_InitOpts:  Debug: -1
151105 18:14:57 6988 secgsi_InitOpts:  CA dir: /etc/grid-security/certificates
151105 18:14:57 6988 secgsi_InitOpts:  CA verification level: 1
151105 18:14:57 6988 secgsi_InitOpts:  CRL dir: /etc/grid-security/certificates/
151105 18:14:57 6988 secgsi_InitOpts:  CRL extension: .r0
151105 18:14:57 6988 secgsi_InitOpts:  CRL check level: 1
151105 18:14:57 6988 secgsi_InitOpts:  CRL refresh time: 86400
151105 18:14:57 6988 secgsi_InitOpts:  Certificate: /etc/grid-security/xrd/xrdcert.pem
151105 18:14:57 6988 secgsi_InitOpts:  Key: /etc/grid-security/xrd/xrdkey.pem
151105 18:14:57 6988 secgsi_InitOpts:  Proxy delegation option: 0
151105 18:14:57 6988 secgsi_InitOpts:  GRIDmap file: /etc/grid-security/grid-mapfile
151105 18:14:57 6988 secgsi_InitOpts:  GRIDmap option: 1
151105 18:14:57 6988 secgsi_InitOpts:  GRIDmap cache entries expiration (secs): 600
151105 18:14:57 6988 secgsi_InitOpts:  Client proxy availability in XrdSecEntity.endorsement: 0
151105 18:14:57 6988 secgsi_InitOpts:  VOMS option: 1
151105 18:14:57 6988 secgsi_InitOpts:  MonInfo option: 1
151105 18:14:57 6988 secgsi_InitOpts:  Crypto modules: ssl
151105 18:14:57 6988 secgsi_InitOpts:  Ciphers: aes-128-cbc:bf-cbc:des-ede3-cbc
151105 18:14:57 6988 secgsi_InitOpts:  MDigests: sha1:md5
151105 18:14:57 6988 secgsi_InitOpts: *** ------------------------------------------------------------ ***
151105 18:14:57 6988 secgsi_XrdOucGMap: cannot access grid map file '/etc/grid-security/grid-mapfile'in read mode; errno: 2 - aborting
=====> sec.protocol /usr/lib64 gsi -certdir:/etc/grid-security/certificates -cert:/etc/grid-security/xrd/xrdcert.pem -key:/etc/grid-security/xrd/xrdkey.pem -crl:1 -moninfo
Config 1 authentication directives processed in /etc/xrootd/xrootd-lfs.cfg
------ Authentication system initialization completed.
Config Routing for se1.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se1.accre.vanderbilt.edu Dest=[::129.59.197.244]:1094
++++++ File system initialization started.
=====> all.role manager
=====> ofs.authorize
++++++ Storage system initialization started.
=====> oss.namelib /usr/lib64/libXrdCmsTfc.so file:/etc/xrootd/storage-lfs.xml?protocol=direct 
=====> all.export /
Plugin No such file or directory loading namelib /usr/lib64/libXrdCmsTfc-4.so
Config Falling back to using /usr/lib64/libXrdCmsTfc.so
Plugin loaded unversioned XrdOucgetName2Name from namelib /usr/lib64/libXrdCmsTfc.so
Copr. 2009 University of Nebraska-Lincoln TFC plugin v 1.0
Params: file:/etc/xrootd/storage-lfs.xml?protocol=direct
Xerces-c has been initialized.
Connecting to the catalog file:/etc/xrootd/storage-lfs.xml?protocol=direct
Using catalog file /etc/xrootd/storage-lfs.xml
No lfn2pfn mapping for /
No lfn2pfn mapping for /
No lfn2pfn mapping for /
Config effective /etc/xrootd/xrootd-lfs.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.namelib /usr/lib64/libXrdCmsTfc.so
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path / r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
++++++ Authorization system initialization started.
151105 18:14:57 6988 acc_Config: Authorization system using configuration in /etc/xrootd/xrootd-lfs.cfg
=====> acc.authdb /etc/xrootd/Authfile
=====> acc.audit deny grant
Config 2 authorization directives processed in /etc/xrootd/xrootd-lfs.cfg
Config 1 auth entries processed in /etc/xrootd/Authfile
------ Authorization system initialization completed.
++++++ Configuring manager role. . .
=====> all.manager meta all cmsxrootd.fnal.gov+ 1213
=====> all.manager se1.accre.vanderbilt.edu:1214
=====> all.adminpath /var/run/xrootd
Config 1 manager(s) started.
Config effective /etc/xrootd/xrootd-lfs.cfg ofs configuration:
       all.role manager
       ofs.authorize
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /var/run/xrootd/lfs/.ofs/posc.log
       ofs.trace      0
------ File system manager initialization completed.
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
151105 18:14:57 7008 cms_Finder: Connected to cmsd via /var/run/xrootd/lfs/.olb/olbd.nimda
151105 18:14:57 7006 cms_ClientMan: Connected to suspended se1.accre.vanderbilt.edu v 3
------ xrootd protocol initialization completed.
------ xrootd lfs@se1.accre.vanderbilt.edu:1094 initialization completed.

==> /var/log/xrootd/lfs/cmsd-lfs.log <==
151105 18:14:57 6902 Protocol: Logged into T2_US_Nebraska xrootd.unl.edu
151105 18:14:57 6883 ManTree: Now connected to 2 root node(s)
151105 18:14:57 6883 Protocol: Logged into T1_US_FNAL cmsxrootd1.fnal.gov
151105 18:14:57 6883 Manager: cmsxrootd1.fnal.gov manager configuration differs from xrootd.unl.edu for site T2_US_Vanderbilt; making file location unpredictable!
151105 18:15:01 7010 State: Status changed to active
151105 18:15:01 7011 Protocol: Primary server.3702:25@se4:1094 logged in.
=====> Routing for se4.accre.vanderbilt.edu: local pub4 prv4 
=====> Route all4: se4.accre.vanderbilt.edu Dest=[::129.59.197.238]:1094

==> /var/log/xrootd/lfs/xrootd-lfs.log <==
151105 18:15:01 7006 cms_setStatus: Manager se1.accre.vanderbilt.edu resumed

==> /var/log/xrootd/lfs/cmsd-lfs.log <==
151105 18:15:01 7316 Protocol: Primary server.18876:29@se7:1094 logged in.
=====> Routing for se7.accre.vanderbilt.edu: local pub4 prv4 
=====> Route all4: se7.accre.vanderbilt.edu Dest=[::129.59.197.240]:1094
151105 18:15:01 7297 Protocol: Primary server.6879:28@se6:1094 logged in.
=====> Routing for se6.accre.vanderbilt.edu: local pub4 prv4 
=====> Route all4: se6.accre.vanderbilt.edu Dest=[::129.59.197.245]:1094
151105 18:15:01 7012 Protocol: Primary server.10773:26@se9:1094 logged in.
=====> Routing for se9.accre.vanderbilt.edu: local pub4 prv4 
=====> Route all4: se9.accre.vanderbilt.edu Dest=[::129.59.197.232]:1094
151105 18:15:01 7317 Protocol: Primary T2_US_Vanderbilt server.4900:32@se8:1094 logged in.
=====> Routing for se8.accre.vanderbilt.edu: local pub4 prv4 
=====> Route all4: se8.accre.vanderbilt.edu Dest=[::129.59.197.227]:1094

==> /var/log/xrootd/lfs/xrootd-lfs.log <==
151105 18:15:07 6993 slot6.1247519:7@e384.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:07 6993 XrootdXeq: slot6.1247519:7@e384.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:07 6993 slot6.1247519:7@e384.chtc.wisc.edu XrootdProtocol: redirecting to se4.accre.vanderbilt.edu:1094
151105 18:15:08 6992 slot13.3338578:25@e025.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:08 6992 XrootdXeq: slot13.3338578:25@e025.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:09 6992 slot13.3338578:25@e025.chtc.wisc.edu XrootdProtocol: redirecting to se9.accre.vanderbilt.edu:1094
151105 18:15:12 7576 slot10.1020073:26@e093.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:12 7576 XrootdXeq: slot10.1020073:26@e093.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:12 7576 slot10.1020073:26@e093.chtc.wisc.edu XrootdProtocol: redirecting to se7.accre.vanderbilt.edu:1094
151105 18:15:21 6993 slot19.1106753:28@e337.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:21 6993 XrootdXeq: slot19.1106753:28@e337.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:21 6993 slot19.1106753:28@e337.chtc.wisc.edu XrootdProtocol: redirecting to se6.accre.vanderbilt.edu:1094
151105 18:15:27 8076 slot13.1770562:29@e302.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:27 8076 XrootdXeq: slot13.1770562:29@e302.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:27 6992 dntaylor.29496:27@g19n12.hep.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:27 8076 slot13.1770562:29@e302.chtc.wisc.edu XrootdProtocol: redirecting to se8.accre.vanderbilt.edu:1094
151105 18:15:27 6992 XrootdXeq: dntaylor.29496:27@g19n12.hep.wisc.edu pub IP46 login as 3e567681.0
151105 18:15:27 6992 dntaylor.29496:27@g19n12.hep.wisc.edu XrootdProtocol: redirecting to se4.accre.vanderbilt.edu:1094
151105 18:15:34 7576 dntaylor.6394:31@g26n30.hep.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:34 7576 XrootdXeq: dntaylor.6394:31@g26n30.hep.wisc.edu pub IP46 login as 3e567681.0
151105 18:15:34 7576 dntaylor.6394:31@g26n30.hep.wisc.edu XrootdProtocol: redirecting to se9.accre.vanderbilt.edu:1094
151105 18:15:36 10272 slot15.565572:32@e334.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:36 10272 XrootdXeq: slot15.565572:32@e334.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:36 10272 slot15.565572:32@e334.chtc.wisc.edu XrootdProtocol: redirecting to se7.accre.vanderbilt.edu:1094
151105 18:15:49 6993 slot13.2750297:30@e099.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:49 6993 XrootdXeq: slot13.2750297:30@e099.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:49 6993 slot13.2750297:30@e099.chtc.wisc.edu XrootdProtocol: redirecting to se6.accre.vanderbilt.edu:1094
151105 18:15:52 10272 slot13.2750297:30@e099.chtc.wisc.edu XrootdProtocol: redirecting to se8.accre.vanderbilt.edu:1094
151105 18:15:52 10272 slot13.2750297:30@e099.chtc.wisc.edu XrootdProtocol: redirecting to se4.accre.vanderbilt.edu:1094
151105 18:15:56 8076 slot5.1917661:34@e020.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:56 8076 XrootdXeq: slot5.1917661:34@e020.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:15:56 8076 slot5.1917661:34@e020.chtc.wisc.edu XrootdProtocol: redirecting to se9.accre.vanderbilt.edu:1094
151105 18:15:58 6992 dntaylor.32151:35@g27n05.hep.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:15:58 6992 XrootdXeq: dntaylor.32151:35@g27n05.hep.wisc.edu pub IP46 login as 3e567681.0
151105 18:15:58 6992 dntaylor.32151:35@g27n05.hep.wisc.edu XrootdProtocol: redirecting to se7.accre.vanderbilt.edu:1094
151105 18:16:03 6993 slot4.740970:33@e223.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:03 6993 XrootdXeq: slot4.740970:33@e223.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:03 6993 slot4.740970:33@e223.chtc.wisc.edu XrootdProtocol: redirecting to se6.accre.vanderbilt.edu:1094
151105 18:16:03 7576 slot5.1917661:34@e020.chtc.wisc.edu XrootdProtocol: redirecting to se8.accre.vanderbilt.edu:1094
151105 18:16:11 10271 slot29.1094233:36@e337.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:11 10271 XrootdXeq: slot29.1094233:36@e337.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:11 10271 slot29.1094233:36@e337.chtc.wisc.edu XrootdProtocol: redirecting to se4.accre.vanderbilt.edu:1094
151105 18:16:24 6992 slot19.2752115:37@e099.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:24 6992 XrootdXeq: slot19.2752115:37@e099.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:24 6992 slot19.2752115:37@e099.chtc.wisc.edu XrootdProtocol: redirecting to se9.accre.vanderbilt.edu:1094
151105 18:16:32 8076 slot17.1683198:38@e067.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:32 8076 XrootdXeq: slot17.1683198:38@e067.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:32 8076 slot17.1683198:38@e067.chtc.wisc.edu XrootdProtocol: redirecting to se7.accre.vanderbilt.edu:1094
151105 18:16:35 6993 cmsu0028.632:40@t2bat0286.cmsaf.mit.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:35 6993 XrootdXeq: cmsu0028.632:40@t2bat0286.cmsaf.mit.edu pub IPv4 login as f4cd8e78.0
151105 18:16:35 6993 cmsu0028.632:40@t2bat0286.cmsaf.mit.edu XrootdProtocol: redirecting to se6.accre.vanderbilt.edu:1094
151105 18:16:39 10271 slot6.2849302:41@atlas99.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:39 10271 XrootdXeq: slot6.2849302:41@atlas99.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:39 6992 slot16.799073:42@e352.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:39 10271 slot6.2849302:41@atlas99.chtc.wisc.edu XrootdProtocol: redirecting to se8.accre.vanderbilt.edu:1094
151105 18:16:39 6992 XrootdXeq: slot16.799073:42@e352.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:40 6992 slot16.799073:42@e352.chtc.wisc.edu XrootdProtocol: redirecting to se4.accre.vanderbilt.edu:1094
151105 18:16:43 7576 slot24.1796918:43@e107.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:43 7576 XrootdXeq: slot24.1796918:43@e107.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:43 7576 slot24.1796918:43@e107.chtc.wisc.edu XrootdProtocol: redirecting to se9.accre.vanderbilt.edu:1094
151105 18:16:51 10272 slot2.3082768:44@e173.chtc.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:51 8076 dntaylor.20922:45@g14n22.hep.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:51 8076 XrootdXeq: dntaylor.20922:45@g14n22.hep.wisc.edu pub IP46 login as 3e567681.0
151105 18:16:51 10272 XrootdXeq: slot2.3082768:44@e173.chtc.wisc.edu pub IPv4 login as 3e567681.0
151105 18:16:51 10272 slot2.3082768:44@e173.chtc.wisc.edu XrootdProtocol: redirecting to se7.accre.vanderbilt.edu:1094
151105 18:16:51 8076 dntaylor.20922:45@g14n22.hep.wisc.edu XrootdProtocol: redirecting to se6.accre.vanderbilt.edu:1094
151105 18:16:55 10271 dntaylor.10608:46@g12n05.hep.wisc.edu XrootdProtocol: more auth requested; sz=2420
151105 18:16:55 10271 XrootdXeq: dntaylor.10608:46@g12n05.hep.wisc.edu pub IP46 login as 3e567681.0
151105 18:16:55 10271 dntaylor.10608:46@g12n05.hep.wisc.edu XrootdProtocol: redirecting to se8.accre.vanderbilt.edu:1094
[root@se1 ~]# xrootd -v
v4.2.3
```

**Comment by abh3** [comment]
Well, I am confused as well. I am getting a machine setup with an infinite limit to see if I can see what might be the issue. However, looking at the log files it isn't apparent to me what is happening that causes a problem other than the log file has nothing in it after initialization completes and the other one does, right?

**Comment by PerilousApricot** [comment]
Well, trying to connect as a client in the first case bombs and works in the second case as well. In sept when I first reported the bug, I left it for a whole day and nothing happened.

**Comment by PerilousApricot** [comment]
That being said, shouldn't

(ulimit -u unlimited ; xrootd)

do the trick?

-- 
It's dark in this basement.

**Comment by wyang007** [comment]
this will not do the trick.

in “man bash”: 

A hard limit cannot be increased by a non-root user  once  it  is
set; a soft limit may be increased up to the value of the hard limits.

So you can use "ulimit -H -a” (shell, not C-shell) to print out the hard limits.



Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

**Comment by PerilousApricot** [comment]
Whoops, I wiffed on the inheritance of ulimits. I thought processes inherited ulimits from their parents, and /etc/security/limits.conf was just defaults for new sessions. I thought setting ulimit as root then changing users would've propagated the limit. Changing limits.conf is the other option instead of having to build a whole new machine.

In either case, it doesn't change the behavior of the server. I just did the following (dashes separate different terminals)

```
[root@se1 xrootd]# ( ulimit -u 2048 ; /etc/init.d/xrootd restart test )
Shutting down xrootd (xrootd, test):                       [  OK  ]
Starting xrootd (xrootd, test):                            [  OK  ]
---
[meloam@vmps11] $ xrdcp -f -v -d 1 root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts .
Set debug level 1
151105 23:58:27 001 Xrd: main: (C) 2004-2011 by the XRootD collaboration. Version: v3.1.0
151105 23:58:27 001 Xrd: Create: (C) 2004-2010 by the Xrootd group. XrdClient $Revision$ - Xrootd version: v3.1.0
151105 23:58:27 001 Xrd: ShowUrls: The converted URLs count is 1
151105 23:58:27 001 Xrd: ShowUrls: URL n.1: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts.
151105 23:58:27 001 Xrd: ShowUrls: The converted URLs count is 1
151105 23:58:27 001 Xrd: ShowUrls: URL n.1: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts.
151105 23:58:27 001 Xrd: Open: Access to server granted.
151105 23:58:27 001 Xrd: Open: Opening the remote file /home/meloam/xrootd-test/hosts
151105 23:58:27 001 Xrd: Open: File open in progress.
151105 23:58:27 001 Xrd: main: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts --> .//hosts
[xrootd] Total 0.00 MB	|====================| 100.00 % [inf MB/s]
[xrdcp] #################################################################
[xrdcp] # Source Name              : root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts
[xrdcp] # Destination Name         : ./hosts
[xrdcp] # Data Copied [bytes]      : 192
[xrdcp] # Realtime [s]             : 0.001000
[xrdcp] # Eff.Copy. Rate[MB/s]     : 0.192000
[xrdcp] #################################################################
Low level caching info:
 StallsRate=0.5
 StallsCount=1
 ReadsCounter=2
 BytesUsefulness=1
 BytesSubmitted=192 BytesHit=192

XrdClient counters:
 ReadBytes:                 192
 WrittenBytes:              0
 WriteRequests:             0
 ReadRequests:              1
 ReadMisses:                0
 ReadHits:                  1
 ReadMissRate:              0.000000
 ReadVRequests:             0
 ReadVSubRequests:          0
 ReadVSubChunks:            0
 ReadVBytes:                0
 ReadVAsyncRequests:        0
 ReadVAsyncSubRequests:     0
 ReadVAsyncSubChunks:       0
 ReadVAsyncBytes:           0
 ReadAsyncRequests:         1
 ReadAsyncBytes:            192
----
[root@se1 xrootd]# ( ulimit -u ; /etc/init.d/xrootd restart test )
unlimited
Shutting down xrootd (xrootd, test):                       [  OK  ]
Starting xrootd (xrootd, test):                            [  OK  ]
----
[meloam@vmps11] $ xrdcp -f -v -d 1 root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts .
Set debug level 1
151105 23:58:41 001 Xrd: main: (C) 2004-2011 by the XRootD collaboration. Version: v3.1.0
151105 23:58:41 001 Xrd: Create: (C) 2004-2010 by the Xrootd group. XrdClient $Revision$ - Xrootd version: v3.1.0
151105 23:58:41 001 Xrd: ShowUrls: The converted URLs count is 1
151105 23:58:41 001 Xrd: ShowUrls: URL n.1: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts.
151105 23:58:41 001 Xrd: ShowUrls: The converted URLs count is 1
151105 23:58:41 001 Xrd: ShowUrls: URL n.1: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts.
151105 23:59:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151105 23:59:41 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:00:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:00:41 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:01:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:01:41 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:02:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:02:41 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:03:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:03:41 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:03:41 001 Xrd: DoHandShake: Failed to read 4 bytes. Retrying ...
151106 00:03:41 001 Xrd: GetAccessToSrv: HandShake failed with server [se1.accre.vanderbilt.edu:1095]
151106 00:03:41 001 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 NotValid
151106 00:03:41 001 Xrd: DumpPhyConn: Phyconn entry, key='Trashed connection', LogCnt=1 NotValid
151106 00:03:41 001 Xrd: Open: Access to server failed: error: 10000 () - retrying.
151106 00:03:41 001 Xrd: Open: Connection attempt failed. Sleeping 5 seconds.
151106 00:03:46 001 Xrd: ShowUrls: The converted URLs count is 1
151106 00:03:46 001 Xrd: ShowUrls: URL n.1: root://se1.accre.vanderbilt.edu:1095//home/meloam/xrootd-test/hosts.
151106 00:04:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='meloam@se1.accre.vanderbilt.edu:1095', LogCnt=1 Valid
151106 00:04:11 48917 Xrd: DumpPhyConn: Phyconn entry, key='Trashed connection', LogCnt=0 NotValid
^C
```

Restarting the test server with ```xrd.trace all``` yields the following log:

```
151106 00:36:02 29869 Starting on Linux 2.6.32-431.el6.x86_64
Copr.  2004-2012 Stanford University, xrd version v4.2.3
++++++ xrootd test@se1.accre.vanderbilt.edu initialization started.
Config using configuration file /etc/xrootd/xrootd-test.cfg
=====> xrd.port 1095
=====> xrd.trace all
Config maximum number of connections restricted to 64000
Config maximum number of threads restricted to -1
151106 00:36:02 29869 XrdConfig: sendfile enabled.
151106 00:36:02 29869 XrdSched: scheduling underused thread monitor in 780 seconds
151106 00:36:02 29869 XrdScheduler: Thread limit has been reached!
151106 00:36:02 29869 XrdSched: Starting with 0 workers
151106 00:36:02 29869 XrdLink: Allocating 8 link objects at a time
151106 00:36:02 29869 XrdPoll: Starting poller 0
151106 00:36:02 29869 XrdPoll: Starting poller 1
151106 00:36:02 29869 XrdPoll: Starting poller 2
151106 00:36:02 29869 XrdProtocol: getting port from protocol xrootd
151106 00:36:02 29869 XrdConfig: LCL port 1095 wsz=87380 (87380)
151106 00:36:02 29869 XrdProtocol: getting protocol object xrootd
Copr.  2012 Stanford University, xrootd protocol 3.0.0 version v4.2.3
++++++ xrootd protocol initialization started.
=====> all.export /home/meloam/xrootd-test/
Config exporting /home/meloam/xrootd-test/
Config warning: 'xrootd.seclib' not specified; strong authentication disabled!
Config Routing for se1.accre.vanderbilt.edu: local pub4 prv4 
Config Route all4: se1.accre.vanderbilt.edu Dest=[::129.59.197.244]:1095
++++++ File system initialization started.
=====> ofs.authorize
++++++ Storage system initialization started.
=====> all.export /home/meloam/xrootd-test/
Config effective /etc/xrootd/xrootd-test.cfg oss configuration:
       oss.alloc        0 0 0
       oss.cachescan    600
       oss.fdlimit      32000 64000
       oss.maxsize      0
       oss.trace        0
       oss.xfr          1 deny 10800 keep 1200
       oss.memfile off  max 33751465984
       oss.defaults  r/w  nocheck nodread nomig norcreate nopurge nostage xattr
       oss.path /home/meloam/xrootd-test/ r/w  nocheck nodread nomig norcreate nopurge nostage xattr
------ Storage system initialization completed.
++++++ Authorization system initialization started.
151106 00:36:02 29869 acc_Config: Authorization system using configuration in /etc/xrootd/xrootd-test.cfg
=====> acc.authdb /etc/xrootd/Authfile-test
=====> acc.audit deny grant
Config 2 authorization directives processed in /etc/xrootd/xrootd-test.cfg
Config 1 auth entries processed in /etc/xrootd/Authfile-test
------ Authorization system initialization completed.
Config effective /etc/xrootd/xrootd-test.cfg ofs configuration:
       all.role server
       ofs.authorize
       ofs.maxdelay   60
       ofs.persist    manual hold 600 logdir /tmp/test/.ofs/posc.log
       ofs.trace      0
------ File system server initialization completed.
151106 00:36:02 29869 XrdSched: scheduling xrootd protocol anchor in 3600 seconds
Config warning: 'xrootd.prepare logdir' not specified; prepare tracking disabled.
------ xrootd protocol initialization completed.
------ xrootd test@se1.accre.vanderbilt.edu:1095 initialization completed.
```

**Comment by xrootd-dev** [comment]
I think you can do something like this:

$ cat /etc/security/limits.d/90-nproc.conf 
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.

*          soft    nproc     1024
root       soft    nproc     unlimited


You can put a reasonably large # there but perhaps not “unlimited” for non-root. By default, each thread use 2-10MB stack space (see “ulimit -s”) so if you have 1024 threads, that is 2-10GB of RAM.

regards,
Wei Yang  |  yangw@slac.stanford.edu  |  650-926-3338(O)

**Comment by PerilousApricot** [comment]
Yep! That works just the same as changing the limit from the command line.
The problem is that there's a regression that makes the server behave
incorrectly if the limit is unlimited.

-- 
It's dark in this basement.

**Comment by PerilousApricot** [comment]
Ah, I think I misunderstood what you were trying to say, Wei. The server works fine with this workaround, so I don't need help getting it to start. However, I'm trying to provide information to help debug why this is getting tripped up.

**Comment by abh3** [comment]
Hi Andrew,

OK, I found the problem. It will be corrected in 4.3.0 that will be 
comming out soon. As for now, avoid using an infinite nproc limit. Thank 
you for pointing out that we never properly fixed this.

Andy

**Comment by PerilousApricot** [comment]
Awesome! I'm super curious about the issue. I stared at XrdScheduler and
couldn't find out how -1 would fall through

-- 
It's dark in this basement.

**Comment by xrootd-dev** [comment]
It all had to do about using RLIM_INFINITY vs -1 which is confusing until 
you realize that rlim.max is unsigned.

Andy
